### ISSUE TITLE
BC break in recent change

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/core-bundle#115]
this change did a BC break for any applications that configured admin extensions, like the sandbox does:
https://github.com/symfony-cmf/CoreBundle/commit/5c87bb98760a04cec267092c49b6f8c5cfc70d09#commitcomment-4948382

```
extensions:
    cmf_core.admin_extension.publish_workflow.time_period:
        implements:
            - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
```

i propose that we revert that, the name is not perfect but its not important enough to warrant the BC break imho.
