### ISSUE TITLE
Migration SF2.8 => SF3.4

### ISSUE THREAD

**Issue by YaaSSDD** [symfony-cmf/core-bundle#270]
Hello I have a problem that I can not solve in spite of the corrections to be applied following the resolved issues and the official doc my problem is to reveal following the migration of Symfony towards the 3.4 and the passage to the 1.3 of CMF core bundle my mistake is this :

```
Unrecognized option "use_sonata_admin" under "cmf_core.persistence.orm"
```
my cmf conf to config.yml :
```
cmf_core:
    persistence:
        orm:
            enabled: true
            manager_name: ~
            use_sonata_admin: auto

```
