### ISSUE TITLE
Remove MultilangAdmin's

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/core-bundle#47]
It seems we now have the possiblity of removing the MultilangAdmin classes by using the new Extension feature of sonata_admin, something like:

```
sonata_admin
  extension:
    cmf_core.admin_extension_multilang:
         implements: Foo/Bar/GetSetLocaleInterface
```

This would I guess apply to RoutingBundle, ContentBundle, MenuBundle and maybe some others.

Need to decide on an interface to implement (or another way of identifying which Documents need the extension).
