### ISSUE TITLE
[AdminExtensions] make the form groups configurable

### ISSUE THREAD

**Issue by uwej711** [symfony-cmf/core-bundle#86]
and default to form.group_general

N.B. I can do the PR if this is OK for others something like 

```
cmf_core:
    admin:
        extensions:
            translateable:
                form_group: my-group
```

or maybe make it configurable per admin class ... that probably would make more sense, but looks not so easy without changes to sonata admin.

changing this in the admin class seems not possible since the extension gets called after configureFormFields.
